# Generated by Django 5.1.4 on 2025-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
        ),
    ]
